backend:
  name: github
  repo: Voormedia/innego # Path to your GitHub repository
  branch: main # Branch to update (master by default)

media_folder: "images/uploads" # Folder where user uploaded files should go
collections: # A list of collections the CMS should be able to edit
  - label: "Sections"
    name: "sections"
    files:
      - label: "Contact"
        name: "contact"
        file: "content/contact.yml"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Company name, name: company-name, widget: string}
          - {label: Company address, name: company-address, widget: markdown}
          - {label: Phone number, name: phone, widget: string}
          - {label: Email address, name: email, widget: string}
          - {label: Background image, name: background, widget: image}
      - label: "References"
        name: "references"
        file: "content/references.yml"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: text}
          - label: Reference
            name: reference
            widget: list
            fields:
              - {label: Content, name: content, widget: text}
              - {label: Author name, name: author-name, widget: string}
              - {label: Author title, name: author-title, widget: string}
              - {label: Author image, name: author-image, widget: image}
              - {label: Author logotype, name: author-logo, widget: image}
              - {label: Background image, name: background-image, widget: image}
      - label: "Projects"
        name: "projects"
        file: "content/projects.yml"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: text}
          - label: Project
            name: project
            widget: list
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Content, name: content, widget: text}
              - {label: Image, name: image, widget: image}
      - label: "About"
        name: "about"
        file: "content/about.yml"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: text}
          - {label: Content, name: content, widget: markdown}
          - {label: Large image, name: largeimg, widget: image}
          - {label: Reference text, name: reference-text, widget: text, required: false}
          - {label: Reference image, name: reference-image, widget: image, required: false}
          - {label: Reference author, name: reference-author, widget: text, required: false}
          - {label: Reference author title, name: reference-author-title, widget: text, required: false}
      - label: "Services"
        name: "services"
        file: "content/services.yml"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: text}
          - label: Service
            name: service
            widget: list
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Content, name: content, widget: text}
              - {label: Image, name: image, widget: image}
      - label: "Hero section"
        name: "hero"
        file: "contents/hero.yml"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: text}
          - {label: Button text, name: cta-text, widget: string}
          - {label: Background image, name: background, widget: image}
