backend:
  name: github
  repo: Voormedia/innego # Path to your GitHub repository
  branch: main # Branch to update (master by default)

media_folder: "images/uploads" # Folder where user uploaded files should go
collections: # A list of collections the CMS should be able to edit
  - label: "Sections"
    name: "sections"
    files:
      - label: "Hero section"
        name: "hero"
        file: "source/content/hero.yml"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: text}
          - {label: Contact me text, name: cta-text, widget: text}
          - {label: Background image, name: background, widget: image}

