backend:
  name: github
  repo: Voormedia/innego # Path to your GitHub repository
  branch: main # Branch to update (master by default)

media_folder: "images/uploads" # Folder where user uploaded files should go
collections: # A list of collections the CMS should be able to edit
  - label: "Pages"
    name: "pages"
    files:
      - label: "About Page"
        name: "about"
        file: "site/content/about.yml"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
          - label: Team
            name: team
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Position, name: position, widget: string}
              - {label: Photo, name: photo, widget: image}
      - label: "Locations Page"
        name: "locations"
        file: "site/content/locations.yml"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
          - label: Locations
            name: locations
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Address, name: address, widget: string}
      # - label: "Services"
      #   name: "services"
      #   widget: "list"
      #   fields:
      #     - {label: Title, name: title, widget: string, default: "Introduction header"}
      #     - {label: Body, name: body, widget: text, default: "Lorem ipsum"}
      #     - label: Service
      #       name: service
      #       widget: object
      #       fields:
      #         - {label: Title, name: title, widget: string, default: "Service"}
      #         - {label: Body, name: body, widget: text, default: "Lorem ipsum"}
      #         - {label: Duration, name: duration, widget: string, default: ""}
      #         - {label: Call to action text, name: call-to-action-text, widget: string, default: "Call to action"}
      #         - {label: Call to action link, name: call-to-action-link, widget: string, default: "#"}
      # - label: "About"
      #   name: "about"
      #   widget: "list"
      #   fields:
      #     - {label: Title, name: title, widget: string, default: "Introduction header"}
      #     - {label: Left content, name: left-content, widget: markdown, default: ""}
      #     - {label: Right image, name: right-image, widget: image}
      #     - {label: Right content, name: right-content, widget: markdown, default: ""}
      #     - {label: Left image, name: left-image, widget: image}
      # - label: "References"
      #   name: "references"
      #   widget: "list"
      #   fields:
      #     - {label: Title, name: title, widget: string, default: "Introduction header"}
      #     - label: Reference
      #       name: reference
      #       widget: object
      #       fields:
      #         - {label: Title, name: title, widget: string, default: "Service"}
      #         - {label: Body, name: body, widget: text, default: "Lorem ipsum"}
      #         - {label: Author, name: author, widget: string}
      # - label: "Contact"
      #   name: "contact"
      #   widget: "list"
      #   fields:
      #     - {label: Title, name: title, widget: string, default: "Introduction header"}
      #     - {label: Body, name: body, widget: text, default: "Lorem ipsum"}
      #     - {label: Email, name: email, widget: text, default: "info@website.com"}

