backend:
  name: github
  repo: Voormedia/innego # Path to your GitHub repository
  branch: main # Branch to update (master by default)

media_folder: "images/uploads" # Folder where user uploaded files should go
collections: # A list of collections the CMS should be able to edit
  - name: "hero" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Hero" # Used in the UI, ie.: "New Post"
    folder: "source/sections" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Sub title", name: "sub-title", widget: "text"}
      - {label: "Contact me text", name: "contact-me-text", widget: string, default: "Contact me"}
      - {label: "Background image", name: "hero-background", widget: image, required: false}
  - name: "projects" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Projects" # Used in the UI, ie.: "New Post"
    folder: "source/projects" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Sub title", name: "sub-title", widget: "text"}
      - label: Projects
        name: projects
        widget: list
        types:
          - label: Project
            name: project
            fields:
              - label: Title
                name: title
              - label: Content
                name: content
                widget: text
          - label: Team Section
            name: team-section
            fields:
              - label: People
                name: people
                widget: list
                fields:
                  - label: Name
                    name: name
      # - label: "Services"
      #   name: "services"
      #   widget: "list"
      #   fields:
      #     - {label: Title, name: title, widget: string, default: "Introduction header"}
      #     - {label: Body, name: body, widget: text, default: "Lorem ipsum"}
      #     - label: Service
      #       name: service
      #       widget: object
      #       fields:
      #         - {label: Title, name: title, widget: string, default: "Service"}
      #         - {label: Body, name: body, widget: text, default: "Lorem ipsum"}
      #         - {label: Duration, name: duration, widget: string, default: ""}
      #         - {label: Call to action text, name: call-to-action-text, widget: string, default: "Call to action"}
      #         - {label: Call to action link, name: call-to-action-link, widget: string, default: "#"}
      # - label: "About"
      #   name: "about"
      #   widget: "list"
      #   fields:
      #     - {label: Title, name: title, widget: string, default: "Introduction header"}
      #     - {label: Left content, name: left-content, widget: markdown, default: ""}
      #     - {label: Right image, name: right-image, widget: image}
      #     - {label: Right content, name: right-content, widget: markdown, default: ""}
      #     - {label: Left image, name: left-image, widget: image}
      # - label: "References"
      #   name: "references"
      #   widget: "list"
      #   fields:
      #     - {label: Title, name: title, widget: string, default: "Introduction header"}
      #     - label: Reference
      #       name: reference
      #       widget: object
      #       fields:
      #         - {label: Title, name: title, widget: string, default: "Service"}
      #         - {label: Body, name: body, widget: text, default: "Lorem ipsum"}
      #         - {label: Author, name: author, widget: string}
      # - label: "Contact"
      #   name: "contact"
      #   widget: "list"
      #   fields:
      #     - {label: Title, name: title, widget: string, default: "Introduction header"}
      #     - {label: Body, name: body, widget: text, default: "Lorem ipsum"}
      #     - {label: Email, name: email, widget: text, default: "info@website.com"}

